# Generated by Django 4.2 on 2023-05-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='salary',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_sold',
        ),
    ]
