# Generated by Django 4.2 on 2024-01-31 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_thread_post'),
        ('item', '0003_rename_price_item_salary_remove_item_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conversation.thread'),
        ),
    ]
